import { Question, Answers } from "./types.js";

const arr = (a: Answers, id: string): string[] =>
  (Array.isArray(a[id]) ? (a[id] as string[]) : []) ?? [];
const has = (a: Answers, id: string, val: string) => arr(a, id).includes(val);
const is = (a: Answers, id: string, val: unknown) => a[id] === val;
const truthy = (a: Answers, id: string) => Boolean(a[id]);

const hasAnyFrontend = (a: Answers) =>
  ["web", "desktop", "extension", "ios", "android"].some((p) =>
    has(a, "platforms", p)
  );
const hasWeb = (a: Answers) => has(a, "platforms", "web");
const hasMobile = (a: Answers) =>
  has(a, "platforms", "ios") || has(a, "platforms", "android");
const isApiOnly = (a: Answers) =>
  has(a, "platforms", "api-only") && !hasAnyFrontend(a);

export const questions: Question[] = [
  // ─────────────────────────────────────────────────────────────
  // 1. Identity (1–10)
  // ─────────────────────────────────────────────────────────────
  {
    id: "name",
    category: "Identity",
    type: "text",
    label: "Project name?",
    placeholder: "e.g. KeyMaster, Linear, Notion",
    required: true,
  },
  {
    id: "tagline",
    category: "Identity",
    type: "text",
    label: "One-line tagline?",
    placeholder: "The simplest way to track office keys.",
    required: true,
  },
  {
    id: "description",
    category: "Identity",
    type: "text",
    label: "2–3 sentence description.",
    placeholder: "What it does and who it's for, in plain language.",
    required: true,
  },
  {
    id: "audience",
    category: "Identity",
    type: "text",
    label: "Target audience?",
    placeholder: "e.g. office managers at 20–500 person companies",
    required: true,
  },
  {
    id: "problem",
    category: "Identity",
    type: "text",
    label: "What problem does it solve?",
    placeholder: "The pain point users have today.",
    required: true,
  },
  {
    id: "motivation",
    category: "Identity",
    type: "text",
    label: "Why now / why you? (optional)",
    placeholder: "Trigger, insight, or personal motivation. Leave blank to skip.",
  },
  {
    id: "projectType",
    category: "Identity",
    type: "select",
    label: "What kind of project is this?",
    options: [
      { value: "saas-product", label: "SaaS product" },
      { value: "internal-tool", label: "Internal tool" },
      { value: "open-source-app", label: "Open-source app" },
      { value: "library", label: "Library / SDK" },
      { value: "prototype", label: "Prototype / experiment" },
    ],
    defaultValue: "saas-product",
  },
  {
    id: "license",
    category: "Identity",
    type: "select",
    label: "License?",
    options: [
      {
        value: "MIT",
        label: "MIT",
        hint: "Permissive. Do anything, just keep the copyright notice. Most popular for OSS.",
      },
      {
        value: "Apache-2.0",
        label: "Apache 2.0",
        hint: "Permissive + explicit patent grant. Preferred by many enterprises.",
      },
      {
        value: "BSD-3-Clause",
        label: "BSD 3-Clause",
        hint: "Permissive, similar to MIT but with a no-endorsement clause.",
      },
      {
        value: "GPL-3.0",
        label: "GPL 3.0",
        hint: "Copyleft. Anything built on top must also be GPL-3.0-licensed.",
      },
      {
        value: "AGPL-3.0",
        label: "AGPL 3.0",
        hint: "Strong copyleft. Even network/SaaS use counts as distribution.",
      },
      {
        value: "MPL-2.0",
        label: "MPL 2.0",
        hint: "Weak copyleft. File-level — only modified files must stay open.",
      },
      {
        value: "Unlicense",
        label: "Unlicense / public domain",
        hint: "No restrictions, no attribution required. Effectively public domain.",
      },
      {
        value: "proprietary",
        label: "Proprietary / closed-source",
        hint: "All rights reserved. No OSS license — the default for most commercial apps.",
      },
      {
        value: "undecided",
        label: "Undecided",
        hint: "Flag it as an open question. Agent will ask before committing.",
      },
    ],
    defaultValue: "proprietary",
  },
  {
    id: "timeline",
    category: "Identity",
    type: "select",
    label: "Build timeline?",
    options: [
      { value: "weekend", label: "Weekend MVP" },
      { value: "weeks", label: "A few weeks" },
      { value: "months", label: "A few months" },
      { value: "ongoing", label: "Ongoing / no deadline" },
    ],
    defaultValue: "weeks",
  },
  {
    id: "successMetric",
    category: "Identity",
    type: "text",
    label: "What does success look like? (optional)",
    placeholder: "e.g. 100 paying teams, or: I use it daily.",
  },

  // ─────────────────────────────────────────────────────────────
  // 2. Users & Auth (11–20)
  // ─────────────────────────────────────────────────────────────
  {
    id: "hasAccounts",
    category: "Users & Auth",
    type: "confirm",
    label: "Does the app have user accounts?",
    defaultValue: true,
  },
  {
    id: "authMethods",
    category: "Users & Auth",
    type: "multiselect",
    label: "Which sign-in methods?",
    options: [
      { value: "email-password", label: "Email + password" },
      { value: "magic-link", label: "Magic link (email code)" },
      { value: "google", label: "Google" },
      { value: "github", label: "GitHub" },
      { value: "apple", label: "Apple" },
      { value: "microsoft", label: "Microsoft" },
      { value: "sso-saml", label: "SSO / SAML" },
    ],
    defaultValue: ["email-password", "google"],
    skipIf: (a) => !truthy(a, "hasAccounts"),
  },
  {
    id: "emailVerification",
    category: "Users & Auth",
    type: "confirm",
    label: "Require email verification on signup?",
    defaultValue: true,
    skipIf: (a) =>
      !truthy(a, "hasAccounts") || !has(a, "authMethods", "email-password"),
  },
  {
    id: "passwordReset",
    category: "Users & Auth",
    type: "confirm",
    label: "Password reset flow?",
    defaultValue: true,
    skipIf: (a) =>
      !truthy(a, "hasAccounts") || !has(a, "authMethods", "email-password"),
  },
  {
    id: "mfa",
    category: "Users & Auth",
    type: "confirm",
    label: "Multi-factor authentication?",
    defaultValue: false,
    skipIf: (a) => !truthy(a, "hasAccounts"),
  },
  {
    id: "hasRoles",
    category: "Users & Auth",
    type: "confirm",
    label: "Do users have different roles / permissions?",
    defaultValue: true,
    skipIf: (a) => !truthy(a, "hasAccounts"),
  },
  {
    id: "rolesList",
    category: "Users & Auth",
    type: "text",
    label: "List the roles (comma-separated).",
    placeholder: "user, admin, superuser",
    defaultValue: "user, admin",
    skipIf: (a) => !truthy(a, "hasAccounts") || !truthy(a, "hasRoles"),
  },
  {
    id: "hasTeams",
    category: "Users & Auth",
    type: "confirm",
    label: "Support teams / workspaces / organizations?",
    defaultValue: false,
    skipIf: (a) => !truthy(a, "hasAccounts"),
  },
  {
    id: "hasBilling",
    category: "Users & Auth",
    type: "confirm",
    label: "Paid accounts / subscriptions?",
    defaultValue: false,
    skipIf: (a) => !truthy(a, "hasAccounts"),
  },
  {
    id: "profileFields",
    category: "Users & Auth",
    type: "text",
    label: "Extra profile fields beyond name/email? (or \"none\")",
    placeholder: "avatar, bio, phone",
    defaultValue: "none",
    skipIf: (a) => !truthy(a, "hasAccounts"),
  },

  // ─────────────────────────────────────────────────────────────
  // 3. Platforms (21–30)
  // ─────────────────────────────────────────────────────────────
  {
    id: "platforms",
    category: "Platforms",
    type: "multiselect",
    label: "Which platforms?",
    options: [
      { value: "web", label: "Web app" },
      { value: "ios", label: "iOS" },
      { value: "android", label: "Android" },
      { value: "desktop", label: "Desktop (Electron/Tauri)" },
      { value: "cli", label: "CLI tool" },
      { value: "extension", label: "Browser extension" },
      { value: "api-only", label: "API only (no UI)" },
    ],
    defaultValue: ["web"],
    allowCustom: false,
  },
  {
    id: "primaryPlatform",
    category: "Platforms",
    type: "select",
    label: "Which is the primary platform?",
    options: [
      { value: "web", label: "Web" },
      { value: "mobile", label: "Mobile" },
      { value: "desktop", label: "Desktop" },
      { value: "cli", label: "CLI" },
      { value: "extension", label: "Extension" },
      { value: "api", label: "API" },
    ],
    skipIf: (a) => arr(a, "platforms").length <= 1,
  },
  {
    id: "marketingSite",
    category: "Platforms",
    type: "confirm",
    label: "Public marketing / landing site?",
    defaultValue: true,
    skipIf: (a) => isApiOnly(a),
  },
  {
    id: "adminDashboard",
    category: "Platforms",
    type: "confirm",
    label: "Admin dashboard (internal ops / moderation)?",
    defaultValue: false,
  },
  {
    id: "responsive",
    category: "Platforms",
    type: "confirm",
    label: "Must the web app work well on mobile browsers?",
    defaultValue: true,
    skipIf: (a) => !hasWeb(a),
  },
  {
    id: "pwa",
    category: "Platforms",
    type: "confirm",
    label: "Installable PWA / offline support on web?",
    defaultValue: false,
    skipIf: (a) => !hasWeb(a),
  },
  {
    id: "mobileOffline",
    category: "Platforms",
    type: "confirm",
    label: "Mobile app needs offline mode?",
    defaultValue: false,
    skipIf: (a) => !hasMobile(a),
  },
  {
    id: "sharedCodebase",
    category: "Platforms",
    type: "confirm",
    label: "Share code across platforms (e.g. React Native + Next)?",
    defaultValue: false,
    skipIf: (a) => arr(a, "platforms").length <= 1,
  },
  {
    id: "publicApi",
    category: "Platforms",
    type: "confirm",
    label: "Expose a public API for third parties?",
    defaultValue: false,
  },
  {
    id: "embeddable",
    category: "Platforms",
    type: "confirm",
    label: "Offer an embeddable widget (iframe / script tag)?",
    defaultValue: false,
  },

  // ─────────────────────────────────────────────────────────────
  // 4. Stack (31–40)
  // ─────────────────────────────────────────────────────────────
  {
    id: "languagePref",
    category: "Stack",
    type: "select",
    label: "Primary language preference?",
    options: [
      { value: "typescript", label: "TypeScript" },
      { value: "javascript", label: "JavaScript" },
      { value: "python", label: "Python" },
      { value: "go", label: "Go" },
      { value: "rust", label: "Rust" },
      { value: "elixir", label: "Elixir" },
      { value: "no-pref", label: "No preference — agent picks" },
    ],
    defaultValue: "typescript",
  },
  {
    id: "frontendFramework",
    category: "Stack",
    type: "select",
    label: "Frontend framework?",
    options: [
      { value: "nextjs", label: "Next.js (App Router)" },
      { value: "react", label: "React (Vite)" },
      { value: "remix", label: "Remix" },
      { value: "vue", label: "Vue / Nuxt" },
      { value: "svelte", label: "Svelte / SvelteKit" },
      { value: "solid", label: "Solid / SolidStart" },
      { value: "astro", label: "Astro" },
      { value: "react-native", label: "React Native / Expo" },
      { value: "no-pref", label: "No preference" },
    ],
    defaultValue: "nextjs",
    skipIf: (a) => !hasAnyFrontend(a),
  },
  {
    id: "backendFramework",
    category: "Stack",
    type: "select",
    label: "Backend framework?",
    options: [
      { value: "nextjs-routes", label: "Next.js API routes (fullstack)" },
      { value: "hono", label: "Hono" },
      { value: "express", label: "Express" },
      { value: "fastify", label: "Fastify" },
      { value: "nestjs", label: "NestJS" },
      { value: "fastapi", label: "FastAPI (Python)" },
      { value: "django", label: "Django (Python)" },
      { value: "rails", label: "Rails (Ruby)" },
      { value: "go-stdlib", label: "Go stdlib / chi" },
      { value: "no-pref", label: "No preference" },
    ],
    defaultValue: "nextjs-routes",
  },
  {
    id: "fullstackOrSplit",
    category: "Stack",
    type: "select",
    label: "Architecture?",
    options: [
      { value: "fullstack", label: "Fullstack framework (same repo, same app)" },
      { value: "split", label: "Separate frontend + backend services" },
      { value: "no-pref", label: "No preference — agent picks" },
    ],
    defaultValue: "fullstack",
    skipIf: (a) => !hasAnyFrontend(a) || isApiOnly(a),
  },
  {
    id: "styling",
    category: "Stack",
    type: "select",
    label: "CSS approach?",
    options: [
      { value: "tailwind", label: "Tailwind CSS" },
      { value: "css-modules", label: "CSS Modules" },
      { value: "styled-components", label: "styled-components / Emotion" },
      { value: "vanilla", label: "Plain CSS" },
      { value: "no-pref", label: "No preference" },
    ],
    defaultValue: "tailwind",
    skipIf: (a) => !hasAnyFrontend(a),
  },
  {
    id: "uiLibrary",
    category: "Stack",
    type: "select",
    label: "UI component library?",
    options: [
      { value: "shadcn", label: "shadcn/ui" },
      { value: "radix", label: "Radix primitives (custom-styled)" },
      { value: "mui", label: "Material UI" },
      { value: "chakra", label: "Chakra UI" },
      { value: "mantine", label: "Mantine" },
      { value: "none", label: "None — build from scratch" },
      { value: "no-pref", label: "No preference" },
    ],
    defaultValue: "shadcn",
    skipIf: (a) => !hasAnyFrontend(a),
  },
  {
    id: "testing",
    category: "Stack",
    type: "multiselect",
    label: "Testing setup?",
    options: [
      { value: "vitest", label: "Vitest (unit)" },
      { value: "jest", label: "Jest (unit)" },
      { value: "playwright", label: "Playwright (e2e)" },
      { value: "cypress", label: "Cypress (e2e)" },
      { value: "none-mvp", label: "None for MVP" },
    ],
    defaultValue: ["vitest"],
  },
  {
    id: "packageManager",
    category: "Stack",
    type: "select",
    label: "Package manager?",
    options: [
      { value: "npm", label: "npm" },
      { value: "pnpm", label: "pnpm" },
      { value: "yarn", label: "Yarn" },
      { value: "bun", label: "Bun" },
      { value: "no-pref", label: "No preference" },
    ],
    defaultValue: "npm",
  },
  {
    id: "monorepo",
    category: "Stack",
    type: "confirm",
    label: "Use a monorepo (Turborepo / pnpm workspaces)?",
    defaultValue: false,
  },
  {
    id: "codeQuality",
    category: "Stack",
    type: "multiselect",
    label: "Code quality tools?",
    options: [
      { value: "eslint", label: "ESLint" },
      { value: "prettier", label: "Prettier" },
      { value: "biome", label: "Biome (replaces ESLint + Prettier)" },
      { value: "husky", label: "Husky (git hooks)" },
      { value: "lint-staged", label: "lint-staged" },
    ],
    defaultValue: ["eslint", "prettier"],
  },

  // ─────────────────────────────────────────────────────────────
  // 5. Data (41–50)
  // ─────────────────────────────────────────────────────────────
  {
    id: "dbNeeded",
    category: "Data",
    type: "confirm",
    label: "Does the app need a database?",
    defaultValue: true,
  },
  {
    id: "dbType",
    category: "Data",
    type: "select",
    label: "Which database?",
    options: [
      { value: "postgres", label: "PostgreSQL" },
      { value: "mysql", label: "MySQL" },
      { value: "sqlite", label: "SQLite (dev) → Postgres (prod)" },
      { value: "mongodb", label: "MongoDB" },
      { value: "firestore", label: "Firestore" },
      { value: "dynamodb", label: "DynamoDB" },
      { value: "no-pref", label: "No preference" },
    ],
    defaultValue: "postgres",
    skipIf: (a) => !truthy(a, "dbNeeded"),
  },
  {
    id: "orm",
    category: "Data",
    type: "select",
    label: "ORM / query builder?",
    options: [
      { value: "prisma", label: "Prisma" },
      { value: "drizzle", label: "Drizzle ORM" },
      { value: "kysely", label: "Kysely" },
      { value: "typeorm", label: "TypeORM" },
      { value: "sqlalchemy", label: "SQLAlchemy (Python)" },
      { value: "raw", label: "Raw SQL" },
      { value: "no-pref", label: "No preference" },
    ],
    defaultValue: "prisma",
    skipIf: (a) => !truthy(a, "dbNeeded"),
  },
  {
    id: "migrations",
    category: "Data",
    type: "confirm",
    label: "Set up migrations tooling?",
    defaultValue: true,
    skipIf: (a) => !truthy(a, "dbNeeded"),
  },
  {
    id: "seedData",
    category: "Data",
    type: "confirm",
    label: "Include a seed script for dev data?",
    defaultValue: true,
    skipIf: (a) => !truthy(a, "dbNeeded"),
  },
  {
    id: "realtimeSync",
    category: "Data",
    type: "confirm",
    label: "Need real-time sync (live updates across clients)?",
    defaultValue: false,
  },
  {
    id: "fileStorage",
    category: "Data",
    type: "confirm",
    label: "Store files / images / user uploads?",
    defaultValue: false,
  },
  {
    id: "storageProvider",
    category: "Data",
    type: "select",
    label: "Storage provider?",
    options: [
      { value: "s3", label: "AWS S3" },
      { value: "r2", label: "Cloudflare R2" },
      { value: "supabase", label: "Supabase Storage" },
      { value: "gcs", label: "Google Cloud Storage" },
      { value: "uploadthing", label: "UploadThing" },
      { value: "local", label: "Local filesystem (dev)" },
      { value: "no-pref", label: "No preference — agent picks" },
    ],
    defaultValue: "r2",
    skipIf: (a) => !truthy(a, "fileStorage"),
  },
  {
    id: "searchNeeded",
    category: "Data",
    type: "confirm",
    label: "Need full-text or semantic search?",
    defaultValue: false,
  },
  {
    id: "caching",
    category: "Data",
    type: "select",
    label: "Caching layer?",
    options: [
      { value: "redis", label: "Redis / Upstash" },
      { value: "memory", label: "In-process memory" },
      { value: "cdn", label: "CDN / edge cache only" },
      { value: "none", label: "None for MVP" },
    ],
    defaultValue: "none",
  },

  // ─────────────────────────────────────────────────────────────
  // 6. Core Features (51–60)
  // ─────────────────────────────────────────────────────────────
  {
    id: "topFeatures",
    category: "Core Features",
    type: "text",
    label: "List 3–5 must-have features (comma-separated).",
    placeholder: "track keys, issue/return flow, audit history, admin roles",
    required: true,
  },
  {
    id: "features",
    category: "Core Features",
    type: "multiselect",
    label: "Which capabilities does the app have?",
    options: [
      { value: "feed", label: "Feed / timeline" },
      { value: "crud-dashboard", label: "CRUD dashboards / lists" },
      { value: "docs-editor", label: "Document / rich-text editor" },
      { value: "notifications", label: "Notifications" },
      { value: "chat", label: "Messaging / chat" },
      { value: "comments", label: "Comments / threads" },
      { value: "scheduling", label: "Calendar / scheduling" },
      { value: "maps", label: "Maps / geolocation" },
      { value: "ai-llm", label: "AI / LLM integration" },
      { value: "file-upload", label: "File uploads" },
      { value: "search-ui", label: "Search UI" },
      { value: "charts", label: "Charts / analytics views" },
    ],
    defaultValue: [],
  },
  {
    id: "userFlows",
    category: "Core Features",
    type: "text",
    label: "Describe the primary user journey in one sentence.",
    placeholder: "User signs up, imports a CSV, gets a dashboard, invites team.",
    required: true,
  },
  {
    id: "sharing",
    category: "Core Features",
    type: "confirm",
    label: "Can users share things publicly (e.g. public links)?",
    defaultValue: false,
  },
  {
    id: "exportImport",
    category: "Core Features",
    type: "confirm",
    label: "Need import/export (CSV, JSON, etc.)?",
    defaultValue: false,
  },
  {
    id: "notificationChannels",
    category: "Core Features",
    type: "multiselect",
    label: "Notification channels?",
    options: [
      { value: "in-app", label: "In-app" },
      { value: "email", label: "Email" },
      { value: "push", label: "Mobile push" },
      { value: "sms", label: "SMS" },
      { value: "slack", label: "Slack" },
      { value: "webhook", label: "Webhook" },
    ],
    defaultValue: ["in-app", "email"],
    skipIf: (a) => !has(a, "features", "notifications"),
  },
  {
    id: "aiUsage",
    category: "Core Features",
    type: "text",
    label: "What does the AI do specifically?",
    placeholder: "Summarize docs, draft emails, answer questions from DB, etc.",
    skipIf: (a) => !has(a, "features", "ai-llm"),
  },
  {
    id: "realtimeFeatures",
    category: "Core Features",
    type: "multiselect",
    label: "Which real-time features are needed?",
    options: [
      { value: "live-updates", label: "Live data updates" },
      { value: "presence", label: "Presence (who's online)" },
      { value: "collab-cursors", label: "Collaborative cursors" },
      { value: "chat", label: "Real-time chat" },
      { value: "notifications-push", label: "Push notifications" },
    ],
    defaultValue: [],
    skipIf: (a) =>
      !truthy(a, "realtimeSync") &&
      !has(a, "features", "chat") &&
      !has(a, "features", "notifications"),
  },
  {
    id: "offlineUse",
    category: "Core Features",
    type: "confirm",
    label: "Does it need to work offline?",
    defaultValue: false,
  },
  {
    id: "contentModeration",
    category: "Core Features",
    type: "confirm",
    label: "User-generated content requiring moderation?",
    defaultValue: false,
    skipIf: (a) =>
      !has(a, "features", "comments") &&
      !has(a, "features", "chat") &&
      !has(a, "features", "feed") &&
      !truthy(a, "sharing"),
  },

  // ─────────────────────────────────────────────────────────────
  // 7. Integrations (61–70)
  // ─────────────────────────────────────────────────────────────
  {
    id: "llmProvider",
    category: "Integrations",
    type: "select",
    label: "LLM provider?",
    options: [
      { value: "claude", label: "Anthropic Claude" },
      { value: "openai", label: "OpenAI" },
      { value: "both", label: "Both / multi-provider" },
      { value: "local", label: "Local (Ollama, llama.cpp)" },
      { value: "other", label: "Other (Groq, Gemini, etc.)" },
      { value: "no-pref", label: "No preference — agent picks" },
    ],
    defaultValue: "claude",
    skipIf: (a) => !has(a, "features", "ai-llm"),
  },
  {
    id: "paymentProvider",
    category: "Integrations",
    type: "select",
    label: "Payment provider?",
    options: [
      { value: "stripe", label: "Stripe" },
      { value: "paddle", label: "Paddle" },
      { value: "lemonsqueezy", label: "Lemon Squeezy" },
      { value: "revenuecat", label: "RevenueCat (mobile)" },
      { value: "no-pref", label: "No preference — agent picks" },
    ],
    defaultValue: "stripe",
    skipIf: (a) => !truthy(a, "hasBilling"),
  },
  {
    id: "pricingModel",
    category: "Integrations",
    type: "select",
    label: "Pricing model?",
    options: [
      { value: "subscription", label: "Subscription (monthly / annual)" },
      { value: "usage", label: "Usage-based" },
      { value: "one-time", label: "One-time purchase" },
      { value: "freemium", label: "Freemium (free tier + paid)" },
      { value: "tiers", label: "Tiered plans" },
    ],
    defaultValue: "freemium",
    skipIf: (a) => !truthy(a, "hasBilling"),
  },
  {
    id: "emailProvider",
    category: "Integrations",
    type: "select",
    label: "Transactional email provider?",
    options: [
      { value: "resend", label: "Resend" },
      { value: "postmark", label: "Postmark" },
      { value: "sendgrid", label: "SendGrid" },
      { value: "ses", label: "AWS SES" },
      { value: "loops", label: "Loops" },
      { value: "none", label: "None for MVP" },
    ],
    defaultValue: "resend",
  },
  {
    id: "analytics",
    category: "Integrations",
    type: "select",
    label: "Product analytics?",
    options: [
      { value: "posthog", label: "PostHog" },
      { value: "plausible", label: "Plausible" },
      { value: "umami", label: "Umami" },
      { value: "ga4", label: "Google Analytics 4" },
      { value: "mixpanel", label: "Mixpanel" },
      { value: "none", label: "None" },
    ],
    defaultValue: "posthog",
  },
  {
    id: "errorTracking",
    category: "Integrations",
    type: "select",
    label: "Error tracking?",
    options: [
      { value: "sentry", label: "Sentry" },
      { value: "rollbar", label: "Rollbar" },
      { value: "bugsnag", label: "Bugsnag" },
      { value: "none", label: "None for MVP" },
    ],
    defaultValue: "sentry",
  },
  {
    id: "cms",
    category: "Integrations",
    type: "select",
    label: "CMS for marketing / docs content?",
    options: [
      { value: "mdx", label: "MDX in repo" },
      { value: "sanity", label: "Sanity" },
      { value: "contentful", label: "Contentful" },
      { value: "notion", label: "Notion as CMS" },
      { value: "payload", label: "Payload CMS" },
      { value: "none", label: "None" },
    ],
    defaultValue: "mdx",
  },
  {
    id: "webhooks",
    category: "Integrations",
    type: "multiselect",
    label: "Webhook support?",
    options: [
      { value: "incoming", label: "Receive webhooks from 3rd parties" },
      { value: "outgoing", label: "Send webhooks to users" },
    ],
    defaultValue: [],
    allowCustom: false,
  },
  {
    id: "otherApis",
    category: "Integrations",
    type: "text",
    label: "Other third-party APIs to integrate? (comma-separated or \"none\")",
    placeholder: "Calendar, Slack, Notion, Linear, etc.",
    defaultValue: "none",
  },
  {
    id: "jobQueue",
    category: "Integrations",
    type: "select",
    label: "Background job / queue system?",
    options: [
      { value: "inngest", label: "Inngest" },
      { value: "trigger-dev", label: "Trigger.dev" },
      { value: "bullmq", label: "BullMQ + Redis" },
      { value: "temporal", label: "Temporal" },
      { value: "cron", label: "Simple cron jobs" },
      { value: "none", label: "None for MVP" },
    ],
    defaultValue: "none",
  },

  // ─────────────────────────────────────────────────────────────
  // 8. Design (71–80)
  // ─────────────────────────────────────────────────────────────
  {
    id: "aesthetic",
    category: "Design",
    type: "select",
    label: "Design aesthetic?",
    options: [
      { value: "minimal-flat", label: "Minimal / flat (Linear, Stripe, Vercel)" },
      { value: "playful", label: "Playful / friendly" },
      { value: "bold", label: "Bold / high-contrast" },
      { value: "corporate", label: "Corporate / enterprise" },
      { value: "brutalist", label: "Brutalist / editorial" },
      { value: "glassmorphic", label: "Glassmorphic / layered" },
    ],
    defaultValue: "minimal-flat",
    skipIf: (a) => !hasAnyFrontend(a),
  },
  {
    id: "primaryColor",
    category: "Design",
    type: "text",
    label: "Primary brand color? (hex or name)",
    placeholder: "#14b8a6 or teal-500",
    defaultValue: "#14b8a6",
    skipIf: (a) => !hasAnyFrontend(a),
  },
  {
    id: "darkMode",
    category: "Design",
    type: "confirm",
    label: "Support dark mode?",
    defaultValue: true,
    skipIf: (a) => !hasAnyFrontend(a),
  },
  {
    id: "density",
    category: "Design",
    type: "select",
    label: "UI density?",
    options: [
      { value: "compact", label: "Compact (data-dense, Linear-like)" },
      { value: "comfortable", label: "Comfortable (default)" },
      { value: "spacious", label: "Spacious (consumer-friendly)" },
    ],
    defaultValue: "comfortable",
    skipIf: (a) => !hasAnyFrontend(a),
  },
  {
    id: "fontFamily",
    category: "Design",
    type: "select",
    label: "Typography vibe?",
    options: [
      { value: "system", label: "System font stack" },
      { value: "geometric-sans", label: "Geometric sans (Inter, Geist)" },
      { value: "humanist-sans", label: "Humanist sans (Source Sans)" },
      { value: "serif", label: "Serif accent" },
      { value: "mono-accent", label: "Mono for headings (brand)" },
      { value: "no-pref", label: "No preference" },
    ],
    defaultValue: "geometric-sans",
    skipIf: (a) => !hasAnyFrontend(a),
  },
  {
    id: "iconSet",
    category: "Design",
    type: "select",
    label: "Icon set?",
    options: [
      { value: "lucide", label: "Lucide" },
      { value: "heroicons", label: "Heroicons" },
      { value: "phosphor", label: "Phosphor" },
      { value: "tabler", label: "Tabler" },
      { value: "custom", label: "Custom SVGs" },
      { value: "no-pref", label: "No preference" },
    ],
    defaultValue: "lucide",
    skipIf: (a) => !hasAnyFrontend(a),
  },
  {
    id: "motion",
    category: "Design",
    type: "select",
    label: "Motion / animation level?",
    options: [
      { value: "minimal", label: "Minimal (transitions only)" },
      { value: "subtle", label: "Subtle (micro-interactions)" },
      { value: "expressive", label: "Expressive (lots of motion)" },
      { value: "none", label: "None" },
    ],
    defaultValue: "subtle",
    skipIf: (a) => !hasAnyFrontend(a),
  },
  {
    id: "accessibility",
    category: "Design",
    type: "select",
    label: "Accessibility target?",
    options: [
      { value: "wcag-aa", label: "WCAG 2.1 AA" },
      { value: "wcag-aaa", label: "WCAG 2.1 AAA" },
      { value: "best-effort", label: "Best-effort, not audited" },
    ],
    defaultValue: "wcag-aa",
    skipIf: (a) => !hasAnyFrontend(a),
  },
  {
    id: "i18n",
    category: "Design",
    type: "confirm",
    label: "Internationalization (multi-language) needed?",
    defaultValue: false,
    skipIf: (a) => !hasAnyFrontend(a),
  },
  {
    id: "rtl",
    category: "Design",
    type: "confirm",
    label: "Support RTL languages (Arabic, Hebrew)?",
    defaultValue: false,
    skipIf: (a) => !hasAnyFrontend(a) || !truthy(a, "i18n"),
  },

  // ─────────────────────────────────────────────────────────────
  // 9. Deploy (81–90)
  // ─────────────────────────────────────────────────────────────
  {
    id: "hosting",
    category: "Deploy",
    type: "select",
    label: "App hosting?",
    options: [
      { value: "vercel", label: "Vercel" },
      { value: "netlify", label: "Netlify" },
      { value: "cloudflare", label: "Cloudflare Pages / Workers" },
      { value: "railway", label: "Railway" },
      { value: "fly", label: "Fly.io" },
      { value: "render", label: "Render" },
      { value: "aws", label: "AWS (ECS / Lambda)" },
      { value: "self-host", label: "Self-host (VPS / Docker)" },
      { value: "undecided", label: "Undecided" },
    ],
    defaultValue: "vercel",
  },
  {
    id: "dbHosting",
    category: "Deploy",
    type: "select",
    label: "Database hosting?",
    options: [
      { value: "supabase", label: "Supabase" },
      { value: "neon", label: "Neon" },
      { value: "planetscale", label: "PlanetScale" },
      { value: "railway", label: "Railway Postgres" },
      { value: "rds", label: "AWS RDS" },
      { value: "self-host", label: "Self-host" },
      { value: "undecided", label: "Undecided" },
    ],
    defaultValue: "supabase",
    skipIf: (a) => !truthy(a, "dbNeeded"),
  },
  {
    id: "domainOwned",
    category: "Deploy",
    type: "confirm",
    label: "Do you already own a domain for this?",
    defaultValue: false,
  },
  {
    id: "cicd",
    category: "Deploy",
    type: "select",
    label: "CI / CD?",
    options: [
      { value: "github-actions", label: "GitHub Actions" },
      { value: "vercel-builds", label: "Vercel built-in" },
      { value: "circleci", label: "CircleCI" },
      { value: "other", label: "Other" },
      { value: "none", label: "None for MVP" },
    ],
    defaultValue: "github-actions",
  },
  {
    id: "environments",
    category: "Deploy",
    type: "select",
    label: "Environment strategy?",
    options: [
      { value: "prod-only", label: "Production only" },
      { value: "prod-staging", label: "Production + staging" },
      { value: "prod-staging-dev", label: "Production + staging + dev" },
    ],
    defaultValue: "prod-staging",
  },
  {
    id: "previewDeploys",
    category: "Deploy",
    type: "confirm",
    label: "Preview deployments per PR?",
    defaultValue: true,
  },
  {
    id: "cdn",
    category: "Deploy",
    type: "confirm",
    label: "CDN / edge network required?",
    defaultValue: true,
    skipIf: (a) => !hasWeb(a) && !isApiOnly(a),
  },
  {
    id: "compliance",
    category: "Deploy",
    type: "multiselect",
    label: "Compliance requirements?",
    options: [
      { value: "gdpr", label: "GDPR" },
      { value: "hipaa", label: "HIPAA" },
      { value: "soc2", label: "SOC 2" },
      { value: "pci", label: "PCI DSS" },
      { value: "ccpa", label: "CCPA" },
    ],
    defaultValue: [],
  },
  {
    id: "uptime",
    category: "Deploy",
    type: "select",
    label: "Uptime target?",
    options: [
      { value: "best-effort", label: "Best-effort (MVP)" },
      { value: "99", label: "99% (standard)" },
      { value: "99.9", label: "99.9% (business)" },
      { value: "99.99", label: "99.99% (enterprise)" },
    ],
    defaultValue: "99",
  },
  {
    id: "secrets",
    category: "Deploy",
    type: "select",
    label: "Secrets management?",
    options: [
      { value: "env-vars", label: "Platform env vars (Vercel / Railway)" },
      { value: "doppler", label: "Doppler" },
      { value: "vault", label: "HashiCorp Vault" },
      { value: "kms", label: "Cloud KMS (AWS / GCP)" },
      { value: "undecided", label: "Undecided" },
    ],
    defaultValue: "env-vars",
  },

  // ─────────────────────────────────────────────────────────────
  // 10. Ops (91–100)
  // ─────────────────────────────────────────────────────────────
  {
    id: "logging",
    category: "Ops",
    type: "select",
    label: "Logging approach?",
    options: [
      { value: "structured", label: "Structured JSON logs (pino, winston)" },
      { value: "console", label: "Plain console logs" },
      { value: "service", label: "Log service (Axiom, Logflare, Datadog)" },
      { value: "later", label: "Figure it out later" },
    ],
    defaultValue: "structured",
  },
  {
    id: "monitoring",
    category: "Ops",
    type: "select",
    label: "Uptime / performance monitoring?",
    options: [
      { value: "sentry-perf", label: "Sentry Performance" },
      { value: "datadog", label: "Datadog" },
      { value: "grafana", label: "Grafana / Prometheus" },
      { value: "betteruptime", label: "Better Uptime" },
      { value: "none", label: "None for MVP" },
    ],
    defaultValue: "none",
  },
  {
    id: "featureFlags",
    category: "Ops",
    type: "confirm",
    label: "Feature flag system?",
    defaultValue: false,
  },
  {
    id: "abTesting",
    category: "Ops",
    type: "confirm",
    label: "A/B testing / experimentation?",
    defaultValue: false,
    skipIf: (a) => !truthy(a, "featureFlags"),
  },
  {
    id: "onboarding",
    category: "Ops",
    type: "confirm",
    label: "Guided onboarding flow / product tour?",
    defaultValue: true,
    skipIf: (a) => !truthy(a, "hasAccounts"),
  },
  {
    id: "supportChannel",
    category: "Ops",
    type: "select",
    label: "User support channel?",
    options: [
      { value: "email", label: "Email (Help Scout, Front)" },
      { value: "chat", label: "In-app chat (Intercom, Crisp)" },
      { value: "docs-only", label: "Docs / FAQ only" },
      { value: "community", label: "Community (Discord, forum)" },
      { value: "none", label: "None for MVP" },
    ],
    defaultValue: "email",
  },
  {
    id: "docs",
    category: "Ops",
    type: "multiselect",
    label: "Which docs sites are needed?",
    options: [
      { value: "user-docs", label: "User-facing help docs" },
      { value: "dev-docs", label: "Developer / API docs" },
      { value: "changelog", label: "Public changelog" },
      { value: "blog", label: "Blog" },
    ],
    defaultValue: [],
  },
  {
    id: "rateLimiting",
    category: "Ops",
    type: "confirm",
    label: "Rate limiting on public endpoints?",
    defaultValue: true,
    skipIf: (a) => !truthy(a, "publicApi") && !truthy(a, "hasAccounts"),
  },
  {
    id: "dataRetention",
    category: "Ops",
    type: "text",
    label: "Data retention / deletion policy? (or \"none\")",
    placeholder: "Delete user data within 30 days of account deletion, etc.",
    defaultValue: "none",
  },
  {
    id: "forbiddenTech",
    category: "Ops",
    type: "text",
    label: "Any technologies to explicitly avoid? (or \"none\")",
    placeholder: "e.g. no MongoDB, no Firebase, no Java",
    defaultValue: "none",
  },
];
